SHEET_TABS = {
    "inventory": "库存清单",
    "events": "低库存记录",
    "item_locations": "商品位置",
    "tasks": "待办任务",
    "history": "购买历史",
    "order_insights": "补货记录",
    "recommendations": "补货推荐",
    "send_log": "运行记录",
}

HEADERS = {
    "库存清单": [
        "商品ID",
        "商品名称",
        "分类",
        "偏好品牌",
        "偏好店铺",
        "存放位置",
        "常购规格",
        "补货阈值",
        "默认紧急度",
        "备注",
    ],
    "低库存记录": [
        "事件ID",
        "记录时间",
        "商品ID",
        "商品名称",
        "来源",
        "紧急度",
        "备注",
        "是否已处理",
        "位置",
    ],
    "商品位置": [
        "位置ID",
        "商品ID",
        "商品名称",
        "位置",
        "默认补货来源",
        "当前状态",
        "备注",
    ],
    "待办任务": [
        "任务ID",
        "创建时间",
        "完成时间",
        "商品ID",
        "商品名称",
        "任务类型",
        "来源位置",
        "目标位置",
        "状态",
        "来源",
        "备注",
    ],
    "购买历史": [
        "购买ID",
        "邮件ID",
        "商品ID",
        "商品名称",
        "购买日期",
        "店铺",
        "品牌",
        "商品标题",
        "规格",
        "价格",
        "收货地址",
        "地址分类",
        "订单链接",
        "满意度",
        "备注",
    ],
    "补货记录": [
        "分析ID",
        "邮件ID",
        "分析日期",
        "商品ID",
        "商品名称",
        "店铺",
        "商品标题",
        "价格",
        "收货地址",
        "地址分类",
        "价格判断",
        "补货预测",
        "健康/适用性提醒",
        "更好建议",
        "置信度",
        "备注",
    ],
    "补货推荐": [
        "推荐ID",
        "推荐日期",
        "商品ID",
        "商品名称",
        "推荐店铺",
        "推荐品牌",
        "推荐商品",
        "预估价格",
        "商品链接",
        "置信度",
        "紧急度",
        "推荐理由",
        "补货状态",
        "最后更新",
    ],
    "运行记录": [
        "日期",
        "处理时间",
        "状态",
        "是否发送邮件",
        "补货推荐数",
        "订单分析数",
        "备注",
    ],
}

DEFAULT_INVENTORY_ROWS = [
    ["toilet_paper", "Toilet Paper", "纸品", "", "Amazon, Costco", "车库,主卧洗手间,汤圆洗手间", "30 rolls", "少于 20%", "中", ""],
    ["paper_towels", "Paper Towels", "纸品", "", "Amazon, Costco", "二层厨房", "12 rolls", "少于 20%", "中", ""],
    ["napkin", "Napkin", "纸品", "", "Amazon, Costco", "二层餐厅", "", "少于 20%", "中", ""],
    ["wet_wipes", "Wet Wipes", "清洁用品", "", "Amazon, Costco", "车库,三层收纳柜", "", "少于 20%", "中", ""],
    ["trash_bags", "Trash Bags", "清洁用品", "", "Amazon, Costco", "二层厨房", "", "少于 20%", "中", ""],
    ["detergent", "Laundry Detergent", "清洁用品", "", "Costco, Amazon", "洗衣区", "", "少于 20%", "中", ""],
    ["body_lotion", "Body Lotion", "个人护理", "", "Amazon, Costco", "汤圆房间", "16 oz", "少于 20%", "中", "给9岁男孩，皮肤容易干，出汗容易痒"],
    ["swiffer_wet_cloth", "Swiffer Wet Cloth", "清洁用品", "Swiffer", "Amazon, Costco", "车库", "", "少于 20%", "中", ""],
    ["pencil", "Pencil", "文具", "", "Amazon, Target", "汤圆房间", "", "少于 20%", "低", ""],
    ["eraser", "Eraser", "文具", "", "Amazon, Target", "汤圆房间", "", "少于 20%", "低", ""],
    ["kids_toothpaste", "Kids Toothpaste", "个人护理", "Tom's of Maine", "Amazon", "汤圆洗手间", "", "少于 20%", "中", "只用 Tom's of Maine Strawberry 儿童牙膏"],
    ["kids_electric_toothbrush", "Kids Electric Toothbrush", "个人护理", "", "Amazon, Costco", "汤圆洗手间", "", "少于 20%", "中", "儿童电动牙刷"],
]
